### ISSUE TITLE
compiled code from commit 30958adec04d5f8d5cd31cb3bfe8e98aca08ee39 , trim is not working even though it says so

### ISSUE THREAD

**Issue by Tsoccerguy3** [PryPurity/WorldBorder#8]
**Describe the bug**:
as of 30958adec04d5f8d5cd31cb3bfe8e98aca08ee39 trim does not work
**Server Version**:

**Plugin Version**:
30958adec04d5f8d5cd31cb3bfe8e98aca08ee39
**Plugins**:
Paper 1.16.1 build 86
![2020-07-10_13 30 26](https://user-images.githubusercontent.com/22108822/87182175-9c917600-c2b1-11ea-82af-e1194838b019.png)
![2020-07-10_13 30 50](https://user-images.githubusercontent.com/22108822/87182178-9d2a0c80-c2b1-11ea-974d-3f1d82fb426d.png)

**Comment by Tsoccerguy3** [comment]
![Failed Trim](https://user-images.githubusercontent.com/22108822/87183431-23475280-c2b4-11ea-98e9-db2f0c633e19.PNG)

**Comment by Tsoccerguy3** [comment]
I have issued this command a number of times and it does nothing /wb trim , /wb trim confirm
i get the same output over and over again even after server reboots . is this not compatible with paper

![2020-07-10_13 58 24](https://user-images.githubusercontent.com/22108822/87184224-9c937500-c2b5-11ea-83d8-5447b3ddbdf3.png)

**Comment by Tsoccerguy3** [comment]
I also tested with spigot 1.16.1 Trim does not work at all

![2020-07-10_19 49 18](https://user-images.githubusercontent.com/22108822/87211229-84881980-c2e6-11ea-8107-52318fad7479.png)

**Comment by Brettflan** [comment]
Some clarification when it reports "trimmed so far" progress. For any "entire region(s)" it says are trimmed ("2" is shown in a screenshot above), those entire region files are deleted from disk and no longer exist. So, there should be no way possible for that to not work, unless you have something else restoring those files.

For "individual chunk(s)", it edits the header portion of the relevant region file(s) to mark those chunk as nonexistent. It doesn't delete the actual chunk data further down in the file, it just allows that portion of the file to potentially be reclaimed or reused by the game server. That header of the region files is stored in memory, which is why it is recommended to restart the server so that header data will be refreshed from the file.
It's remotely possible that something changed in the file format which would prevent this from working, but I doubt it.

There have been many many cases in the past of people reporting Trim as not working, and the problem always came down to cached data on the side of DynMap, still showing trimmed sections that no longer existed.

**Comment by PryPurity** [comment]
This issue is being closed due to this commit not being a fully-released version. Thank you for the clarification, @Brettflan !

**Comment by Tsoccerguy3** [comment]
> 
> 
> Some clarification when it reports "trimmed so far" progress. For any "entire region(s)" it says are trimmed ("2" is shown in a screenshot above), those entire region files are deleted from disk and no longer exist. So, there should be no way possible for that to not work, unless you have something else restoring those files.
> 
> For "individual chunk(s)", it edits the header portion of the relevant region file(s) to mark those chunk as nonexistent. It doesn't delete the actual chunk data further down in the file, it just allows that portion of the file to potentially be reclaimed or reused by the game server. That header of the region files is stored in memory, which is why it is recommended to restart the server so that header data will be refreshed from the file.
> It's remotely possible that something changed in the file format which would prevent this from working, but I doubt it.
> 
> There have been many many cases in the past of people reporting Trim as not working, and the problem always came down to cached data on the side of DynMap, still showing trimmed sections that no longer existed.

Brett , what i have been doing on a local server is manually deleting Dynmaps folder and disabling dynmap in between using worldborder trim and a dynmap render . There is no way for that area of land to just go away and come back. trim is just not working on 1.16.1. even though it says it is .

**Comment by Tsoccerguy3** [comment]
As may know Amulet the Minecraft standalone editor is available https://github.com/Amulet-Team/Amulet-Map-Editor/releases . I loaded the world into the editor to see if the fly out area was trimed , it was not . look at the capture images . Its still there and not a dynmap problem . please open issue

![Amulet Capture](https://user-images.githubusercontent.com/22108822/87226692-79270380-c363-11ea-9d9c-884beb71dee9.PNG)
![Amulet Capture2](https://user-images.githubusercontent.com/22108822/87226693-79bf9a00-c363-11ea-8c98-891dbe9e56d6.PNG)
